name: Build Paper Plugin

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Recovery source code
        uses: actions/checkout@v4

      - name: Setup Java 21 JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build plugin with Maven
        run: mvn clean package --file pom.xml

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GodMacePlugin-1.21.1
          path: target/*.jar
